version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.2-apache-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:  
          keys:  
          - v1-dependencies-{{ checksum "composer.json" }}  
          # fallback to using the latest cache if no exact match is found  
          - v1-dependencies-  
      - run: composer install -n --prefer-dist  
      - save_cache:  
          paths:  
            - ./vendor  
          key: v1-dependencies-{{ checksum "composer.json" }}  
      - run:
          name: Install some basic tools
          command: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install -y nano
            sudo apt-get install -y iputils-ping net-tools
      - run:
          name: Configure & start Apache
          command: sudo service apache2 start
      - run:
          command: |
            setcap cap_net_raw+ep /bin/ping 
            ping 127.0.0.1
      - run:
          name: API TEST
          command: vendor/phpunit/phpunit/phpunit tests/api_test.php
