version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.1-fpm-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
        name: API TEST
        command: vendor/phpunit/phpunit/phpunit tests/api_test.php
