version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/php7.2-apache-browsers

commands:
  restore-composer:
    steps:
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum 'composer.json'}}
          - v1-dependencies-
  save-composer:
    steps:
      - save_cache:
        paths:
          - ./vender
        key: v1-dependencies-{{ checksum 'composer.json'}}

jobs:
  build:
    # docker:
    #   - image: circleci/php:7.2-apache-browsers
    # working_directory: ~/repo
    executor:
      name: default
    steps:
      - checkout
      # - restore-composer
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      # - save-composer
      - run:
          name: Install some basic tools
          command: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install -y nano
            sudo apt-get install -y iputils-ping net-tools
      - run:
          name: Configure & start Apache
          command: sudo service apache2 start
      - run:
          name: API TEST
          command: vendor/phpunit/phpunit/phpunit tests/api_test.php
